### PR TITLE
RS-509: rename bucket with web console

### PR DESCRIPTION
**Pull request by AnthonyCvn**
Closes #

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

feature

### What was changed?

As a user, I can rename bucket with Web Console

### Related issues

No

### Does this PR introduce a breaking change?

Version 1.12: The rename method was introduced.

### CODE REVIEW

**Comment by AnthonyCvn** [comment]
@atimin can you review before I add some tests ?

**Comment by atimin** [comment]
@AnthonyCvn  I've had a look on the UI.  Does it make more sense to put the rename icon in the same column with remove icon? The remove action has a confirmation. I don't see any risks here.

**Comment by AnthonyCvn** [comment]
@atimin I tried both, but you're right, there's no risk, I'll put them in the same column.

**Review by atimin — APPROVED** [review]
Looks great for me. Let's add tests.

**Comment by AnthonyCvn** [comment]
@atimin now the tests are added :)

**Review by atimin — APPROVED** [review]
Perfect!

**Pull request merged**
